# Welcome to Jekyll!
#
title: Mell0wx
description: Welcome to the Mell0wx knowledge base. 
baseurl: /mell0wx # the subpath of your site, e.g. /support
url: https://mell0wx.github.io # the base hostname AND PROTOCOL for your site, e.g. http://example.com
permalink: /:categories/:title

content_type: Knowledge Base #Define whether this is a knowledge base, help center, or something else
use_authors: true #Set this to false to disable showing post authors

brand_logo: logo.png
brand_name: mell0wx
header: Welcome to the Mell0wx Knowledge Base
subheader: What are you looking for?

meta_image: odin-meta.png

# Social Links
#twitter_username: TheTeaGuns
#facebook_page:
github_username: mell0wx
#email: m@credd.in
#linkedin_page:
#instagram_username: 


# Navivation
nav_item_one: Github
nav_item_one_link: https://github.com/mell0wx/

#nav_item_two: Twitter
#nav_item_two_link: https://twitter.com/TheTeaGuns

nav_item_three: #
nav_item_three_link: #

nav_button: Return to Mell0wx Home
nav_button_link: https://mell0wx.github.io/

# More Help
#help_one_title: Odin Bugs
#help_one_content: If you find any bugs or problems with this theme, please open an issue over on Github.
#help_one_button: Github
#help_one_link: https://github.com/TeaGuns/odin/issues

#help_two_title: Twitter
#help_two_content: Feel free to tweet at me if you have suggestions for Odin. Or if you just want to say hi.
#help_two_button: Twitter
#help_two_link: https://twitter.com/theteaguns

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-last-modified-at

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#


sass:
  sass_dir:          _scss
  style:            :compressed
